#!/bin/bash

# This file is a hook for dockerhub. It will use a DEVELOPER=1 build if the tagged version end with -DEVELOPER

DEVELOPER=0
if [[ "$CACHE_TAG" == *-dev ]]; then
    DEVELOPER=1
fi

docker build -f $DOCKERFILE_PATH --build-arg "DEVELOPER=$DEVELOPER" -t $IMAGE_NAME .
